// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	deploymentmanager "google.golang.org/api/deploymentmanager/v2beta"
	googleapi "google.golang.org/api/googleapi"

	mock "github.com/stretchr/testify/mock"
)

// DeploymentsDeleteCallInterface is an autogenerated mock type for the DeploymentsDeleteCallInterface type
type DeploymentsDeleteCallInterface struct {
	mock.Mock
}

// Do provides a mock function with given fields: call, opts
func (_m *DeploymentsDeleteCallInterface) Do(call *deploymentmanager.DeploymentsDeleteCall, opts ...googleapi.CallOption) (*deploymentmanager.Operation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, call)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *deploymentmanager.Operation
	if rf, ok := ret.Get(0).(func(*deploymentmanager.DeploymentsDeleteCall, ...googleapi.CallOption) *deploymentmanager.Operation); ok {
		r0 = rf(call, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deploymentmanager.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*deploymentmanager.DeploymentsDeleteCall, ...googleapi.CallOption) error); ok {
		r1 = rf(call, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
