// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	deploymentmanager "google.golang.org/api/deploymentmanager/v2beta"
	googleapi "google.golang.org/api/googleapi"

	mock "github.com/stretchr/testify/mock"
)

// DeploymentsGetCallInterface is an autogenerated mock type for the DeploymentsGetCallInterface type
type DeploymentsGetCallInterface struct {
	mock.Mock
}

// Do provides a mock function with given fields: call, opts
func (_m *DeploymentsGetCallInterface) Do(call *deploymentmanager.DeploymentsGetCall, opts ...googleapi.CallOption) (*deploymentmanager.Deployment, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, call)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *deploymentmanager.Deployment
	if rf, ok := ret.Get(0).(func(*deploymentmanager.DeploymentsGetCall, ...googleapi.CallOption) *deploymentmanager.Deployment); ok {
		r0 = rf(call, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*deploymentmanager.Deployment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*deploymentmanager.DeploymentsGetCall, ...googleapi.CallOption) error); ok {
		r1 = rf(call, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
