// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	admin "google.golang.org/api/admin/directory/v1"

	googleapi "google.golang.org/api/googleapi"

	mock "github.com/stretchr/testify/mock"
)

// MembersDeleteCallInterface is an autogenerated mock type for the MembersDeleteCallInterface type
type MembersDeleteCallInterface struct {
	mock.Mock
}

// Do provides a mock function with given fields: call, opts
func (_m *MembersDeleteCallInterface) Do(call *admin.MembersDeleteCall, opts ...googleapi.CallOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, call)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*admin.MembersDeleteCall, ...googleapi.CallOption) error); ok {
		r0 = rf(call, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
