// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	cloudidentity "google.golang.org/api/cloudidentity/v1beta1"
	googleapi "google.golang.org/api/googleapi"

	mock "github.com/stretchr/testify/mock"
)

// GroupLookupCallInterface is an autogenerated mock type for the GroupLookupCallInterface type
type GroupLookupCallInterface struct {
	mock.Mock
}

// Do provides a mock function with given fields: call, opts
func (_m *GroupLookupCallInterface) Do(call *cloudidentity.GroupsLookupCall, opts ...googleapi.CallOption) (*cloudidentity.LookupGroupNameResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, call)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *cloudidentity.LookupGroupNameResponse
	if rf, ok := ret.Get(0).(func(*cloudidentity.GroupsLookupCall, ...googleapi.CallOption) *cloudidentity.LookupGroupNameResponse); ok {
		r0 = rf(call, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudidentity.LookupGroupNameResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*cloudidentity.GroupsLookupCall, ...googleapi.CallOption) error); ok {
		r1 = rf(call, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
