// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	logger "github.com/rockholla/go-lib/logger"
	mock "github.com/stretchr/testify/mock"

	v1 "google.golang.org/api/dns/v1"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// DeleteResourceRecordSets provides a mock function with given fields: projectID, managedZone
func (_m *Interface) DeleteResourceRecordSets(projectID string, managedZone string) error {
	ret := _m.Called(projectID, managedZone)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(projectID, managedZone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetResourceRecordSet provides a mock function with given fields: projectID, managedZone, name
func (_m *Interface) GetResourceRecordSet(projectID string, managedZone string, name string) (*v1.ResourceRecordSet, error) {
	ret := _m.Called(projectID, managedZone, name)

	var r0 *v1.ResourceRecordSet
	if rf, ok := ret.Get(0).(func(string, string, string) *v1.ResourceRecordSet); ok {
		r0 = rf(projectID, managedZone, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ResourceRecordSet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(projectID, managedZone, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResourceRecordSets provides a mock function with given fields: projectID, managedZone
func (_m *Interface) GetResourceRecordSets(projectID string, managedZone string) ([]*v1.ResourceRecordSet, error) {
	ret := _m.Called(projectID, managedZone)

	var r0 []*v1.ResourceRecordSet
	if rf, ok := ret.Get(0).(func(string, string) []*v1.ResourceRecordSet); ok {
		r0 = rf(projectID, managedZone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.ResourceRecordSet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(projectID, managedZone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Initialize provides a mock function with given fields: credentials, log
func (_m *Interface) Initialize(credentials string, log logger.Interface) error {
	ret := _m.Called(credentials, log)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, logger.Interface) error); ok {
		r0 = rf(credentials, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetResourceRecordSets provides a mock function with given fields: projectID, managedZone, records
func (_m *Interface) SetResourceRecordSets(projectID string, managedZone string, records []*v1.ResourceRecordSet) error {
	ret := _m.Called(projectID, managedZone, records)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []*v1.ResourceRecordSet) error); ok {
		r0 = rf(projectID, managedZone, records)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
