// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	googleapi "google.golang.org/api/googleapi"

	serviceusage "google.golang.org/api/serviceusage/v1"
)

// ServicesEnableCallInterface is an autogenerated mock type for the ServicesEnableCallInterface type
type ServicesEnableCallInterface struct {
	mock.Mock
}

// Do provides a mock function with given fields: call, opts
func (_m *ServicesEnableCallInterface) Do(call *serviceusage.ServicesBatchEnableCall, opts ...googleapi.CallOption) (*serviceusage.Operation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, call)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *serviceusage.Operation
	if rf, ok := ret.Get(0).(func(*serviceusage.ServicesBatchEnableCall, ...googleapi.CallOption) *serviceusage.Operation); ok {
		r0 = rf(call, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceusage.Operation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*serviceusage.ServicesBatchEnableCall, ...googleapi.CallOption) error); ok {
		r1 = rf(call, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
